### ISSUE TITLE
FTBFS with c-sundry 0~29

### ISSUE THREAD

**Issue by jengelh** [bus1/libbus1#4]
With c-sundry 8deaceba08f06348c3825b2c99b4393e9e589bb9, libbus1 717b601ba4f0dd5d6feafb99e7fd7baf2292ddec no longer builds:
```
[   34s] In file included from src/message.c:14:0:
[   34s] src/message.h:15:9: error: unknown type name 'CRef'
[   34s]          CRef ref;
[   34s]          ^~~~
```

**Comment by EduRam** [comment]
I managed to compile by search&replace "CRef" with "_Atomic unsigned long" on several files.

**Comment by peter-b** [comment]
I have submitted https://github.com/c-util/c-sundry/pull/1 which will resolve this issue.

**Comment by scanf** [comment]
libbus1 is not ready for use, maybe wait till upstream rewrites it before use.

**Comment by dvdhrm** [comment]
The libbus1 library is not needed, anymore. The newer bus1.ko UAPI is simple enough for direct use.

**Comment by peter-b** [comment]
@dvdhrm Could you please add a prominent notice that `libbus1` is not to be used, possibly in `README` and in the repository description? Otherwise there are going to be a lot more people confused by its presence.
